// <auto-generated />
using FDMPrintCostEstimator.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FDMPrintCostEstimator.Data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20251110190651_InitialThree")]
    partial class InitialThree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FDMPrintCostEstimator.Model.Filaments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserDataId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("FDMPrintCostEstimator.Model.Printers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("FDMPrintCostEstimator.Model.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost1kWh")
                        .HasColumnType("REAL");

                    b.Property<string>("CurencySymbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("FDMPrintCostEstimator.Model.Filaments", b =>
                {
                    b.HasOne("FDMPrintCostEstimator.Model.UserData", null)
                        .WithMany("Filament")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("FDMPrintCostEstimator.Model.Printers", b =>
                {
                    b.HasOne("FDMPrintCostEstimator.Model.UserData", null)
                        .WithMany("Printer")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("FDMPrintCostEstimator.Model.UserData", b =>
                {
                    b.Navigation("Filament");

                    b.Navigation("Printer");
                });
#pragma warning restore 612, 618
        }
    }
}
