// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPlanner.Data.Contexts;

#nullable disable

namespace _3DPrintCostEstimator.Data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("_3DPrintCostEstimator.Model.Filaments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserDataId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("_3DPrintCostEstimator.Model.Printers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("_3DPrintCostEstimator.Model.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost1kWh")
                        .HasColumnType("REAL");

                    b.Property<string>("CurencySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("_3DPrintCostEstimator.Model.Filaments", b =>
                {
                    b.HasOne("_3DPrintCostEstimator.Model.UserData", null)
                        .WithMany("Filament")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("_3DPrintCostEstimator.Model.Printers", b =>
                {
                    b.HasOne("_3DPrintCostEstimator.Model.UserData", null)
                        .WithMany("Printer")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("_3DPrintCostEstimator.Model.UserData", b =>
                {
                    b.Navigation("Filament");

                    b.Navigation("Printer");
                });
#pragma warning restore 612, 618
        }
    }
}
